all:
  children:
    webservers:
      hosts:
        ansible-lab:
          ansible_host: 192.168.56.10
          ansible_user: vagrant
          ansible_ssh_private_key_file: "{{ inventory_dir }}/.vagrant/machines/default/libvirt/private_key"
          ansible_ssh_common_args: "-o StrictHostKeyChecking=yes -o UserKnownHostsFile={{ inventory_dir }}/.vagrant/known_hosts"
      vars:
        ansible_python_interpreter: /usr/bin/python3
        flask_port: 5000
